build:
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: 'phpunit --coverage-clover logs/clover.xml'
                coverage:
                    file: 'logs/clover.xml'
                    format: 'clover'
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
checks:
    php: true